language: c

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gcc-arm-none-eabi

before_script:
  - ./ci-install-sdk.sh

script:
  - make -C examples/gpio_toggle/armgcc clean all xDK_TOP=/tmp/nrf52-sdk-for-travis-ci
  
  

  
