language: c

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gcc-arm-none-eabi

before_script:
  - ./common/ci/ci-install-sdk.sh

script:
  - find examples -name "armgcc" | xargs -n1 make -C
  
  
  

  
